//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuraNaming_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuraNaming_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.AuraNaming-en-EN", typeof(AuraNaming_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisoprint LLC.
        /// </summary>
        public static string AnisoprintLLC {
            get {
                return ResourceManager.GetString("AnisoprintLLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisoprint.
        /// </summary>
        public static string AnisoprintName {
            get {
                return ResourceManager.GetString("AnisoprintName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bugs@anisoprint.com.
        /// </summary>
        public static string AuraBugsMailto {
            get {
                return ResourceManager.GetString("AuraBugsMailto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string AuraBugSubject {
            get {
                return ResourceManager.GetString("AuraBugSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2019 Anisoprint LLC.
        /// </summary>
        public static string AuraCopyright {
            get {
                return ResourceManager.GetString("AuraCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aura Beta.
        /// </summary>
        public static string AuraName {
            get {
                return ResourceManager.GetString("AuraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@anisoprint.com.
        /// </summary>
        public static string AuraSupportEmail {
            get {
                return ResourceManager.GetString("AuraSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.9.21.1.
        /// </summary>
        public static string AuraVersion {
            get {
                return ResourceManager.GetString("AuraVersion", resourceCulture);
            }
        }
    }
}
