//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeViewer_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeViewer_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.CodeViewer-en-EN", typeof(CodeViewer_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber cuts.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic extrusions.
        /// </summary>
        public static string ExtrudeP {
            get {
                return ResourceManager.GetString("ExtrudeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic+fiber extrusions.
        /// </summary>
        public static string ExtrudePF {
            get {
                return ResourceManager.GetString("ExtrudePF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code.
        /// </summary>
        public static string GCodeHeader {
            get {
                return ResourceManager.GetString("GCodeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D.
        /// </summary>
        public static string Header2D {
            get {
                return ResourceManager.GetString("Header2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string Header3D {
            get {
                return ResourceManager.GetString("Header3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string LayerEnd {
            get {
                return ResourceManager.GetString("LayerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer index.
        /// </summary>
        public static string LayerIndex {
            get {
                return ResourceManager.GetString("LayerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string LayerStart {
            get {
                return ResourceManager.GetString("LayerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All code.
        /// </summary>
        public static string ModeAllCode {
            get {
                return ResourceManager.GetString("ModeAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ModeBlocks {
            get {
                return ResourceManager.GetString("ModeBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string ModeGeometry {
            get {
                return ResourceManager.GetString("ModeGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One layer.
        /// </summary>
        public static string ModeOneLayer {
            get {
                return ResourceManager.GetString("ModeOneLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ModeRange {
            get {
                return ResourceManager.GetString("ModeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic moves.
        /// </summary>
        public static string MoveP {
            get {
                return ResourceManager.GetString("MoveP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic+fiber moves.
        /// </summary>
        public static string MovePF {
            get {
                return ResourceManager.GetString("MovePF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic retracts.
        /// </summary>
        public static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next layer.
        /// </summary>
        public static string TipLayerNext {
            get {
                return ResourceManager.GetString("TipLayerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous layer.
        /// </summary>
        public static string TipLayerPrevious {
            get {
                return ResourceManager.GetString("TipLayerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travels.
        /// </summary>
        public static string Travels {
            get {
                return ResourceManager.GetString("Travels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string VisibilityHeader {
            get {
                return ResourceManager.GetString("VisibilityHeader", resourceCulture);
            }
        }
    }
}
