//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Common-en-EN", typeof(Common_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new layup.
        /// </summary>
        public static string AddNewLayup {
            get {
                return ResourceManager.GetString("AddNewLayup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add model.
        /// </summary>
        public static string AddNewModel {
            get {
                return ResourceManager.GetString("AddNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new layup region.
        /// </summary>
        public static string AddNewRegion {
            get {
                return ResourceManager.GetString("AddNewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All right reserved.
        /// </summary>
        public static string AllRightReserved {
            get {
                return ResourceManager.GetString("AllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string CloneModel {
            get {
                return ResourceManager.GetString("CloneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Composer firmware.
        /// </summary>
        public static string ComposerFirmwarer {
            get {
                return ResourceManager.GetString("ComposerFirmwarer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy details.
        /// </summary>
        public static string CopyDetailsTitle {
            get {
                return ResourceManager.GetString("CopyDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our support team will be glad to help with your issue. 
        ///For a better response, please attach the project with the issue. .
        /// </summary>
        public static string CourageMessage {
            get {
                return ResourceManager.GetString("CourageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string CreateNewProject {
            get {
                return ResourceManager.GetString("CreateNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project.
        /// </summary>
        public static string DefaultProjectName {
            get {
                return ResourceManager.GetString("DefaultProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth (Y) .
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to display.
        /// </summary>
        public static string DisplayConnecting {
            get {
                return ResourceManager.GetString("DisplayConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is outside the table.
        /// </summary>
        public static string ErrorModelNotInTable {
            get {
                return ResourceManager.GetString("ErrorModelNotInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruders.
        /// </summary>
        public static string Extruders {
            get {
                return ResourceManager.GetString("Extruders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writing error.
        /// </summary>
        public static string FileWritingExceptionCaption {
            get {
                return ResourceManager.GetString("FileWritingExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writing exception.
        /// </summary>
        public static string FileWritingExceptionText {
            get {
                return ResourceManager.GetString("FileWritingExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string FirmItTitle {
            get {
                return ResourceManager.GetString("FirmItTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display is ready.
        /// </summary>
        public static string FirmwareDisplayReady {
            get {
                return ResourceManager.GetString("FirmwareDisplayReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display firmware uploaded.
        /// </summary>
        public static string FirmwareDisplayUpdated {
            get {
                return ResourceManager.GetString("FirmwareDisplayUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading display firmware.
        /// </summary>
        public static string FirmwareDisplayUpdating {
            get {
                return ResourceManager.GetString("FirmwareDisplayUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong firmware file.
        /// </summary>
        public static string FirmwareFileIncorrect {
            get {
                return ResourceManager.GetString("FirmwareFileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer firmware files (*.fw, *fw2)|*.fw; *.fw2.
        /// </summary>
        public static string FirmwareFilter {
            get {
                return ResourceManager.GetString("FirmwareFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload(DEV).
        /// </summary>
        public static string FirmwareItDevTitle {
            get {
                return ResourceManager.GetString("FirmwareItDevTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select port.
        /// </summary>
        public static string FirmwareNoCmbPort {
            get {
                return ResourceManager.GetString("FirmwareNoCmbPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose firmware file.
        /// </summary>
        public static string FirmwareNoPath {
            get {
                return ResourceManager.GetString("FirmwareNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware not verified.
        /// </summary>
        public static string FirmwareNotVerified {
            get {
                return ResourceManager.GetString("FirmwareNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select printer version.
        /// </summary>
        public static string FirmwareNoVersionForDev {
            get {
                return ResourceManager.GetString("FirmwareNoVersionForDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string FirmwarePath {
            get {
                return ResourceManager.GetString("FirmwarePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer model incorrect.
        /// </summary>
        public static string FirmwarePrinterModelIncorrect {
            get {
                return ResourceManager.GetString("FirmwarePrinterModelIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware upload error.
        /// </summary>
        public static string FirmwareUploadError {
            get {
                return ResourceManager.GetString("FirmwareUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading firmware.
        /// </summary>
        public static string FirmwareUploading {
            get {
                return ResourceManager.GetString("FirmwareUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware uploaded successfully.
        /// </summary>
        public static string FirmwareVerified {
            get {
                return ResourceManager.GetString("FirmwareVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        public static string FirmwareVersions {
            get {
                return ResourceManager.GetString("FirmwareVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update started.
        /// </summary>
        public static string FirmwaringStarted {
            get {
                return ResourceManager.GetString("FirmwaringStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to printer.
        /// </summary>
        public static string FirmwaringStarting {
            get {
                return ResourceManager.GetString("FirmwaringStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code file (*.gcode)|*.gcode.
        /// </summary>
        public static string GCodeFilter {
            get {
                return ResourceManager.GetString("GCodeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate code add at least one model. 
        ///Be assured that all models is laying in print area and
        ///has no intersections between themselves  .
        /// </summary>
        public static string GenerationDisabledTooltip {
            get {
                return ResourceManager.GetString("GenerationDisabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project has non-default layup rules.
        /// </summary>
        public static string HasLayupRules {
            get {
                return ResourceManager.GetString("HasLayupRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string HeaderAbout {
            get {
                return ResourceManager.GetString("HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Composer firmware....
        /// </summary>
        public static string HeaderFirmwareComposerA4 {
            get {
                return ResourceManager.GetString("HeaderFirmwareComposerA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open model....
        /// </summary>
        public static string HeaderOpenModel {
            get {
                return ResourceManager.GetString("HeaderOpenModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project....
        /// </summary>
        public static string HeaderOpenProject {
            get {
                return ResourceManager.GetString("HeaderOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        public static string HeaderSaveProject {
            get {
                return ResourceManager.GetString("HeaderSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project as....
        /// </summary>
        public static string HeaderSaveProjectAs {
            get {
                return ResourceManager.GetString("HeaderSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (Z).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not received.
        /// </summary>
        public static string InformationNotReceived {
            get {
                return ResourceManager.GetString("InformationNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer model verified.
        /// </summary>
        public static string InformationReceived {
            get {
                return ResourceManager.GetString("InformationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string IsUniform {
            get {
                return ResourceManager.GetString("IsUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer.
        /// </summary>
        public static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set layup.
        /// </summary>
        public static string LayupModel {
            get {
                return ResourceManager.GetString("LayupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the structure of the part is defined by rules in the slicing tab. Use can override these rules with custom region layup rules. Each layup has the start and the finish height and priority. If region layup rules have intersection by height, the higher priority layup rules will be used for slicing. The priority &quot;1&quot; is the highest..
        /// </summary>
        public static string LayupReference {
            get {
                return ResourceManager.GetString("LayupReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layup rules deleting.
        /// </summary>
        public static string LayupRulesRemoveCaption {
            get {
                return ResourceManager.GetString("LayupRulesRemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all layups settings?.
        /// </summary>
        public static string LayupRulesRemoveText {
            get {
                return ResourceManager.GetString("LayupRulesRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License terms.
        /// </summary>
        public static string LicenseTerms {
            get {
                return ResourceManager.GetString("LicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models should not be intersected between themselves.
        /// </summary>
        public static string MessageHasIntersectionBetweenThemselves {
            get {
                return ResourceManager.GetString("MessageHasIntersectionBetweenThemselves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part brim/skirt should lays in print area.
        /// </summary>
        public static string MessageHasIntersectionBrimSkirtWithPrintArea {
            get {
                return ResourceManager.GetString("MessageHasIntersectionBrimSkirtWithPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part should lays in print area.
        /// </summary>
        public static string MessageHasIntersectionWithPrintArea {
            get {
                return ResourceManager.GetString("MessageHasIntersectionWithPrintArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part shoud has no intersections with wipe tower.
        /// </summary>
        public static string MessageHasIntersectionWithWipeTower {
            get {
                return ResourceManager.GetString("MessageHasIntersectionWithWipeTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set extruder for each part entity.
        /// </summary>
        public static string MessageNoFiberExtruder {
            get {
                return ResourceManager.GetString("MessageNoFiberExtruder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate code load at least one model.
        /// </summary>
        public static string MessageNoModel {
            get {
                return ResourceManager.GetString("MessageNoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D-model file (*.stl, *.step, *.stp, *.3ds, *.obj)|*.stl; *.step; *.stp; *.3ds; *.obj.
        /// </summary>
        public static string ModelFilter {
            get {
                return ResourceManager.GetString("ModelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes in open {PROJECT_NAME} project before quitting?.
        /// </summary>
        public static string OnClosingMessage {
            get {
                return ResourceManager.GetString("OnClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string OnClosingTitle {
            get {
                return ResourceManager.GetString("OnClosingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes in open {PROJECT_NAME} project before open new?.
        /// </summary>
        public static string OpenProjectHasChanges {
            get {
                return ResourceManager.GetString("OpenProjectHasChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string OpenProjectTitle {
            get {
                return ResourceManager.GetString("OpenProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick layup rules from another model.
        /// </summary>
        public static string PickFromModel {
            get {
                return ResourceManager.GetString("PickFromModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to printer.
        /// </summary>
        public static string PrinterConnecting {
            get {
                return ResourceManager.GetString("PrinterConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying printer model .
        /// </summary>
        public static string PrinterModelVerifying {
            get {
                return ResourceManager.GetString("PrinterModelVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer not ready.
        /// </summary>
        public static string PrinterNotReady {
            get {
                return ResourceManager.GetString("PrinterNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer is ready.
        /// </summary>
        public static string PrinterReady {
            get {
                return ResourceManager.GetString("PrinterReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority .
        /// </summary>
        public static string PriorityForConcat {
            get {
                return ResourceManager.GetString("PriorityForConcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aura project (*.auproj)|*.auproj.
        /// </summary>
        public static string ProjectFilter {
            get {
                return ResourceManager.GetString("ProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove model.
        /// </summary>
        public static string RemoveModel {
            get {
                return ResourceManager.GetString("RemoveModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another.
        /// </summary>
        public static string ReportAttachAnotherProject {
            get {
                return ResourceManager.GetString("ReportAttachAnotherProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string ReportAttachCurrentProject {
            get {
                return ResourceManager.GetString("ReportAttachCurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach project.
        /// </summary>
        public static string ReportAttachProject {
            get {
                return ResourceManager.GetString("ReportAttachProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask your question or describe the bug.
        /// </summary>
        public static string ReportDescriptionTitle {
            get {
                return ResourceManager.GetString("ReportDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach generating bug project .
        /// </summary>
        public static string ReportIsEmptyFiles {
            get {
                return ResourceManager.GetString("ReportIsEmptyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach project or/and add description.
        /// </summary>
        public static string ReportIsEmptyFillFields {
            get {
                return ResourceManager.GetString("ReportIsEmptyFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ReportSend {
            get {
                return ResourceManager.GetString("ReportSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report form.
        /// </summary>
        public static string ReportStartDescription {
            get {
                return ResourceManager.GetString("ReportStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string ResizeModel {
            get {
                return ResourceManager.GetString("ResizeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string RotateModel {
            get {
                return ResourceManager.GetString("RotateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string ShiftModel {
            get {
                return ResourceManager.GetString("ShiftModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration can&apos;t be saved.
        /// </summary>
        public static string SystemConfigurationSavingError {
            get {
                return ResourceManager.GetString("SystemConfigurationSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration updated.
        /// </summary>
        public static string SystemConfigurationUpdated {
            get {
                return ResourceManager.GetString("SystemConfigurationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating system configuration.
        /// </summary>
        public static string SystemConfigurationUpdating {
            get {
                return ResourceManager.GetString("SystemConfigurationUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System configuration can&apos;t be updated.
        /// </summary>
        public static string SystemConfigurationWritingError {
            get {
                return ResourceManager.GetString("SystemConfigurationWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string TipApply {
            get {
                return ResourceManager.GetString("TipApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TipCancel {
            get {
                return ResourceManager.GetString("TipCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string TipClone {
            get {
                return ResourceManager.GetString("TipClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfrom to unique layup region.
        /// </summary>
        public static string TipCreateSoloRegion {
            get {
                return ResourceManager.GetString("TipCreateSoloRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TipDelete {
            get {
                return ResourceManager.GetString("TipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TipDeleteCaptionDefault {
            get {
                return ResourceManager.GetString("TipDeleteCaptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all layup settings.
        /// </summary>
        public static string TipDeleteLayupSettings {
            get {
                return ResourceManager.GetString("TipDeleteLayupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this?.
        /// </summary>
        public static string TipDeleteQuestionDefault {
            get {
                return ResourceManager.GetString("TipDeleteQuestionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string TipDown {
            get {
                return ResourceManager.GetString("TipDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string TipDuplicate {
            get {
                return ResourceManager.GetString("TipDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string TipExport {
            get {
                return ResourceManager.GetString("TipExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get layup rules from another region.
        /// </summary>
        public static string TipGetFromAnotherRegion {
            get {
                return ResourceManager.GetString("TipGetFromAnotherRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set layers structure scheme.
        /// </summary>
        public static string TipLayup {
            get {
                return ResourceManager.GetString("TipLayup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize mode.
        /// </summary>
        public static string TipResize {
            get {
                return ResourceManager.GetString("TipResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate mode.
        /// </summary>
        public static string TipRotate {
            get {
                return ResourceManager.GetString("TipRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift mode.
        /// </summary>
        public static string TipShift {
            get {
                return ResourceManager.GetString("TipShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string TipSplit {
            get {
                return ResourceManager.GetString("TipSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string TipUp {
            get {
                return ResourceManager.GetString("TipUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing failed. Check parameters..
        /// </summary>
        public static string UnsuccessSlicing {
            get {
                return ResourceManager.GetString("UnsuccessSlicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (X).
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add correct e-mail.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add you e-mail.
        /// </summary>
        public static string YourEMail {
            get {
                return ResourceManager.GetString("YourEMail", resourceCulture);
            }
        }
    }
}
