//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Fiber_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fiber_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Fiber-en-EN", typeof(Fiber_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new fiber.
        /// </summary>
        public static string AddNewFiber {
            get {
                return ResourceManager.GetString("AddNewFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do plastic retract.
        /// </summary>
        public static string DoPlasticRetract {
            get {
                return ResourceManager.GetString("DoPlasticRetract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish ironing distance (mm).
        /// </summary>
        public static string EndPolygonEmptyDistanceMM {
            get {
                return ResourceManager.GetString("EndPolygonEmptyDistanceMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber extrusion speed (mm/sec).
        /// </summary>
        public static string ExtrusionSpeed {
            get {
                return ResourceManager.GetString("ExtrusionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan speed (%).
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber diameter (mm).
        /// </summary>
        public static string FiberDiameter {
            get {
                return ResourceManager.GetString("FiberDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber type.
        /// </summary>
        public static string FiberType {
            get {
                return ResourceManager.GetString("FiberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber material settings file (*.aumf)|*.aumf.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic flow multiplier.
        /// </summary>
        public static string FlowMultiplier {
            get {
                return ResourceManager.GetString("FlowMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber reinforced perimeters.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string HEADER_OTHER {
            get {
                return ResourceManager.GetString("HEADER_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string HEADER_RESTART {
            get {
                return ResourceManager.GetString("HEADER_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear density (tex = g/km).
        /// </summary>
        public static string LinearDensity {
            get {
                return ResourceManager.GetString("LinearDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-lift on restart (mm).
        /// </summary>
        public static string ZHopF {
            get {
                return ResourceManager.GetString("ZHopF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart pause (sec).
        /// </summary>
        public static string ZHopFPauseAdhesion {
            get {
                return ResourceManager.GetString("ZHopFPauseAdhesion", resourceCulture);
            }
        }
    }
}
