//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Global-en-EN", typeof(Global_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use fiber.
        /// </summary>
        public static string AllowGenerateFiber {
            get {
                return ResourceManager.GetString("AllowGenerateFiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Check print time.
        /// </summary>
        public static string CheckPrintTimeLayer {
            get {
                return ResourceManager.GetString("CheckPrintTimeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid crossing borders.
        /// </summary>
        public static string DoAvoidCrossingPerimeters {
            get {
                return ResourceManager.GetString("DoAvoidCrossingPerimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do coast before retract.
        /// </summary>
        public static string DoCoastAtEnd {
            get {
                return ResourceManager.GetString("DoCoastAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do retract on changing layers.
        /// </summary>
        public static string DoRetractOnLayerChange {
            get {
                return ResourceManager.GetString("DoRetractOnLayerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do retract only when crossing borders.
        /// </summary>
        public static string DoRetractOnlyWhenCrossingPerimeters {
            get {
                return ResourceManager.GetString("DoRetractOnlyWhenCrossingPerimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do wipe nozzle.
        /// </summary>
        public static string DoWipeNozzle {
            get {
                return ResourceManager.GetString("DoWipeNozzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Z-hop when retracted.
        /// </summary>
        public static string DoZHop {
            get {
                return ResourceManager.GetString("DoZHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layer extrusion width coefficient.
        /// </summary>
        public static string FLEWCoeffToNormal {
            get {
                return ResourceManager.GetString("FLEWCoeffToNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layer printing speed (mm/sec).
        /// </summary>
        public static string FLSpeed {
            get {
                return ResourceManager.GetString("FLSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layer height (mm).
        /// </summary>
        public static string FLThickness {
            get {
                return ResourceManager.GetString("FLThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate wipe tower (BETA).
        /// </summary>
        public static string GenerateWipeTower {
            get {
                return ResourceManager.GetString("GenerateWipeTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brim.
        /// </summary>
        public static string HEADER_BRIM {
            get {
                return ResourceManager.GetString("HEADER_BRIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular plastic infill.
        /// </summary>
        public static string HEADER_CELLULAR {
            get {
                return ResourceManager.GetString("HEADER_CELLULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External shell.
        /// </summary>
        public static string HEADER_EXTERNAL_SHELL {
            get {
                return ResourceManager.GetString("HEADER_EXTERNAL_SHELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced entities.
        /// </summary>
        public static string HEADER_FIBER_PRINTING {
            get {
                return ResourceManager.GetString("HEADER_FIBER_PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layer.
        /// </summary>
        public static string HEADER_FIRST_LAYER {
            get {
                return ResourceManager.GetString("HEADER_FIRST_LAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer thickness.
        /// </summary>
        public static string HEADER_LAYER_THICKNESS {
            get {
                return ResourceManager.GetString("HEADER_LAYER_THICKNESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooze prevention.
        /// </summary>
        public static string HEADER_OOZE_PREVENTION {
            get {
                return ResourceManager.GetString("HEADER_OOZE_PREVENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string HEADER_OTHER {
            get {
                return ResourceManager.GetString("HEADER_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string HEADER_PART {
            get {
                return ResourceManager.GetString("HEADER_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic perimeters.
        /// </summary>
        public static string HEADER_PLASTIC_PERIMETERS {
            get {
                return ResourceManager.GetString("HEADER_PLASTIC_PERIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced perimeters.
        /// </summary>
        public static string HEADER_REINFORCED_PERIMETERS {
            get {
                return ResourceManager.GetString("HEADER_REINFORCED_PERIMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirt.
        /// </summary>
        public static string HEADER_SKIRT {
            get {
                return ResourceManager.GetString("HEADER_SKIRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid plastic infill.
        /// </summary>
        public static string HEADER_SOLID {
            get {
                return ResourceManager.GetString("HEADER_SOLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string HEADER_SUPPORT {
            get {
                return ResourceManager.GetString("HEADER_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe tower.
        /// </summary>
        public static string HEADER_WIPE_TOWER {
            get {
                return ResourceManager.GetString("HEADER_WIPE_TOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macrolayer height (mm).
        /// </summary>
        public static string MacroLayerHeight {
            get {
                return ResourceManager.GetString("MacroLayerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum layer print time (sec).
        /// </summary>
        public static string MinLayerTimeForSlowing {
            get {
                return ResourceManager.GetString("MinLayerTimeForSlowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Min print layer time (sec) .
        /// </summary>
        public static string MinPrintTimeLayer {
            get {
                return ResourceManager.GetString("MinPrintTimeLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooze prevention.
        /// </summary>
        public static string OOZE_PREVENTION_HEADER {
            get {
                return ResourceManager.GetString("OOZE_PREVENTION_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter trim ratio.
        /// </summary>
        public static string TrimGapRatio {
            get {
                return ResourceManager.GetString("TrimGapRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use non-default layup rules for parts.
        /// </summary>
        public static string UseLayupRules {
            get {
                return ResourceManager.GetString("UseLayupRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum travel for Z-hop (mm).
        /// </summary>
        public static string ZHopMinimumDistance {
            get {
                return ResourceManager.GetString("ZHopMinimumDistance", resourceCulture);
            }
        }
    }
}
