//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfillFiber_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfillFiber_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.InfillFiber-en-EN", typeof(InfillFiber_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisogrid ribs crossing type.
        /// </summary>
        public static string AnisogridRibPlacementType {
            get {
                return ResourceManager.GetString("AnisogridRibPlacementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate reinforced infills.
        /// </summary>
        public static string GenerateFiberInfills {
            get {
                return ResourceManager.GetString("GenerateFiberInfills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber reinforced infills.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber infill pattern.
        /// </summary>
        public static string InfillFiberType {
            get {
                return ResourceManager.GetString("InfillFiberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On side ribs middle.
        /// </summary>
        public static string RibPlacementTypeMiddle {
            get {
                return ResourceManager.GetString("RibPlacementTypeMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near crossing.
        /// </summary>
        public static string RibPlacementTypeNearApex {
            get {
                return ResourceManager.GetString("RibPlacementTypeNearApex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anisogrid.
        /// </summary>
        public static string TypeAnisogrid {
            get {
                return ResourceManager.GetString("TypeAnisogrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isogrid.
        /// </summary>
        public static string TypeIsogrid {
            get {
                return ResourceManager.GetString("TypeIsogrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rombic grid.
        /// </summary>
        public static string TypeRombicGrid {
            get {
                return ResourceManager.GetString("TypeRombicGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        public static string TypeSolid {
            get {
                return ResourceManager.GetString("TypeSolid", resourceCulture);
            }
        }
    }
}
