//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfillFiberCellular_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfillFiberCellular_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.InfillFiberCellular-en-EN", typeof(InfillFiberCellular_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle between main ribs (°).
        /// </summary>
        public static string AnisogridAngleBetweenMainRibs {
            get {
                return ResourceManager.GetString("AnisogridAngleBetweenMainRibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill density (%).
        /// </summary>
        public static string AnisogridFillDensity {
            get {
                return ResourceManager.GetString("AnisogridFillDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide angle (°).
        /// </summary>
        public static string AnisogridOrientation {
            get {
                return ResourceManager.GetString("AnisogridOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrusion width (mm).
        /// </summary>
        public static string EW {
            get {
                return ResourceManager.GetString("EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infill extension into perimeters.
        /// </summary>
        public static string ExtendIntoPerimeter {
            get {
                return ResourceManager.GetString("ExtendIntoPerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber feedrate (%).
        /// </summary>
        public static string ExtrusionFiberMaxPercent {
            get {
                return ResourceManager.GetString("ExtrusionFiberMaxPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular fiber infill.
        /// </summary>
        public static string HEADER_INFILL_FIBER_CELLULAR {
            get {
                return ResourceManager.GetString("HEADER_INFILL_FIBER_CELLULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill density (%).
        /// </summary>
        public static string IsogridDensity {
            get {
                return ResourceManager.GetString("IsogridDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide angle (°).
        /// </summary>
        public static string IsogridOrientation {
            get {
                return ResourceManager.GetString("IsogridOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum line length (mm).
        /// </summary>
        public static string MinSegmentLength {
            get {
                return ResourceManager.GetString("MinSegmentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill density (%).
        /// </summary>
        public static string RombicGridDensity {
            get {
                return ResourceManager.GetString("RombicGridDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First rib angle (°).
        /// </summary>
        public static string RombicGridFirstRibAngle {
            get {
                return ResourceManager.GetString("RombicGridFirstRibAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second rib angle (°).
        /// </summary>
        public static string RombicGridSecondRibAngle {
            get {
                return ResourceManager.GetString("RombicGridSecondRibAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing speed coefficient.
        /// </summary>
        public static string SpeedCoefficient {
            get {
                return ResourceManager.GetString("SpeedCoefficient", resourceCulture);
            }
        }
    }
}
