//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InsetFiber_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InsetFiber_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.InsetFiber-en-EN", typeof(InsetFiber_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrusion width (mm).
        /// </summary>
        public static string EW {
            get {
                return ResourceManager.GetString("EW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber feedrate (%).
        /// </summary>
        public static string ExtrusionFiberMaxPercent {
            get {
                return ResourceManager.GetString("ExtrusionFiberMaxPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate reinforced perimeters.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced perimeters.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner reinforced perimeters count.
        /// </summary>
        public static string InnerCount {
            get {
                return ResourceManager.GetString("InnerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid plastic layers above fiber count.
        /// </summary>
        public static string MacroLayersOntoFiberCount {
            get {
                return ResourceManager.GetString("MacroLayersOntoFiberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid plastic layers below fiber count.
        /// </summary>
        public static string MacroLayersUnderFiberCount {
            get {
                return ResourceManager.GetString("MacroLayersUnderFiberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!MinFilletRadius.
        /// </summary>
        public static string MinFilletRadius {
            get {
                return ResourceManager.GetString("MinFilletRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer reinforced perimeters count.
        /// </summary>
        public static string OuterCount {
            get {
                return ResourceManager.GetString("OuterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing speed coefficient.
        /// </summary>
        public static string PrintingSpeedCoefficient {
            get {
                return ResourceManager.GetString("PrintingSpeedCoefficient", resourceCulture);
            }
        }
    }
}
