//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Plastic_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Plastic_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Plastic-en-EN", typeof(Plastic_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new plastic.
        /// </summary>
        public static string AddNewMaterial {
            get {
                return ResourceManager.GetString("AddNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build plate temperature on first layers (°C).
        /// </summary>
        public static string BedHeatupOnFLs {
            get {
                return ResourceManager.GetString("BedHeatupOnFLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build plate temperature (°C).
        /// </summary>
        public static string BedHeatupTemperature {
            get {
                return ResourceManager.GetString("BedHeatupTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coast length (mm).
        /// </summary>
        public static string CoastAtEndLength {
            get {
                return ResourceManager.GetString("CoastAtEndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool cost.
        /// </summary>
        public static string CostPerSpool {
            get {
                return ResourceManager.GetString("CostPerSpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default materials.
        /// </summary>
        public static string DefaultMaterials {
            get {
                return ResourceManager.GetString("DefaultMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density (g/cm³).
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable print cooling.
        /// </summary>
        public static string EnablePrintCooling {
            get {
                return ResourceManager.GetString("EnablePrintCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra unretract length (mm).
        /// </summary>
        public static string ExtraLength {
            get {
                return ResourceManager.GetString("ExtraLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unretract speed (mm/sec).
        /// </summary>
        public static string ExtraSpeed {
            get {
                return ResourceManager.GetString("ExtraSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow multiplier.
        /// </summary>
        public static string ExtrusionMultiplier {
            get {
                return ResourceManager.GetString("ExtrusionMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filament diameter (mm).
        /// </summary>
        public static string FilamentDiameter {
            get {
                return ResourceManager.GetString("FilamentDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic materials settings file (*.aump)|*.aump.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layers fan speed height (mm).
        /// </summary>
        public static string FirstLayersFanHeight {
            get {
                return ResourceManager.GetString("FirstLayersFanHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layers temperatures height (mm).
        /// </summary>
        public static string FirstLayersHeightMM {
            get {
                return ResourceManager.GetString("FirstLayersHeightMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        public static string HEADER_COOLING {
            get {
                return ResourceManager.GetString("HEADER_COOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooze prevention.
        /// </summary>
        public static string HEADER_OOZE_PREVENTION {
            get {
                return ResourceManager.GetString("HEADER_OOZE_PREVENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string HEADER_OTHER {
            get {
                return ResourceManager.GetString("HEADER_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string HEADER_TEMPERATURE {
            get {
                return ResourceManager.GetString("HEADER_TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber length in spool (km).
        /// </summary>
        public static string LengthPerSpool {
            get {
                return ResourceManager.GetString("LengthPerSpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material can&apos;t be deleted.
        /// </summary>
        public static string MaterialInSessionCaption {
            get {
                return ResourceManager.GetString("MaterialInSessionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material is used by current session and can&apos;t be deleted.
        /// </summary>
        public static string MaterialInSessionText {
            get {
                return ResourceManager.GetString("MaterialInSessionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum fan speed (%).
        /// </summary>
        public static string MaximumFanSpeed {
            get {
                return ResourceManager.GetString("MaximumFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer time for max fan speed (sec).
        /// </summary>
        public static string MinLayerTimeForCooling {
            get {
                return ResourceManager.GetString("MinLayerTimeForCooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular fan speed (%).
        /// </summary>
        public static string PlasticRegularFanSpeed {
            get {
                return ResourceManager.GetString("PlasticRegularFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic type.
        /// </summary>
        public static string PlasticType {
            get {
                return ResourceManager.GetString("PlasticType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First layers fan speed (%).
        /// </summary>
        public static string PlsticFirstLayersFanSpeed {
            get {
                return ResourceManager.GetString("PlsticFirstLayersFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting material....
        /// </summary>
        public static string RemoveCaption {
            get {
                return ResourceManager.GetString("RemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this material?.
        /// </summary>
        public static string RemoveQuestion {
            get {
                return ResourceManager.GetString("RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction length on tool change (mm).
        /// </summary>
        public static string RetractionLengthOnChangingExtruder {
            get {
                return ResourceManager.GetString("RetractionLengthOnChangingExtruder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction length (mm).
        /// </summary>
        public static string RetractionLengthOnTravel {
            get {
                return ResourceManager.GetString("RetractionLengthOnTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retract speed (mm/sec).
        /// </summary>
        public static string RetractionSpeed {
            get {
                return ResourceManager.GetString("RetractionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction min travel without crossing (mm).
        /// </summary>
        public static string RetractMinimumTravelNoCrossing {
            get {
                return ResourceManager.GetString("RetractMinimumTravelNoCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retraction min travel on crossing (mm).
        /// </summary>
        public static string RetractMinimumTravelOnCrossing {
            get {
                return ResourceManager.GetString("RetractMinimumTravelOnCrossing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spool weight (g).
        /// </summary>
        public static string SpoolWeight {
            get {
                return ResourceManager.GetString("SpoolWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruder temperature on first layers (°C).
        /// </summary>
        public static string TemperatureOnFLs {
            get {
                return ResourceManager.GetString("TemperatureOnFLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruder temperature (°C).
        /// </summary>
        public static string TemperaturePrint {
            get {
                return ResourceManager.GetString("TemperaturePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standby extruder temperature (°C).
        /// </summary>
        public static string TemperatureWait {
            get {
                return ResourceManager.GetString("TemperatureWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new material.
        /// </summary>
        public static string TipAddNewMaterial {
            get {
                return ResourceManager.GetString("TipAddNewMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all materials.
        /// </summary>
        public static string TipExportMaterials {
            get {
                return ResourceManager.GetString("TipExportMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import materials.
        /// </summary>
        public static string TipImportMaterials {
            get {
                return ResourceManager.GetString("TipImportMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User materials.
        /// </summary>
        public static string UserMaterials {
            get {
                return ResourceManager.GetString("UserMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe nozzle length (mm).
        /// </summary>
        public static string WipeNozzleLength {
            get {
                return ResourceManager.GetString("WipeNozzleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-hop height (mm).
        /// </summary>
        public static string ZHopP {
            get {
                return ResourceManager.GetString("ZHopP", resourceCulture);
            }
        }
    }
}
