//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Printer_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Printer_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Printer-en-EN", typeof(Printer_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional retract length (mm).
        /// </summary>
        public static string AdditionalRetractMM {
            get {
                return ResourceManager.GetString("AdditionalRetractMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new printer.
        /// </summary>
        public static string AddNewPrinter {
            get {
                return ResourceManager.GetString("AddNewPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build area (mm).
        /// </summary>
        public static string BuildArea {
            get {
                return ResourceManager.GetString("BuildArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End G-code.
        /// </summary>
        public static string EndGCode {
            get {
                return ResourceManager.GetString("EndGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting extruder.
        /// </summary>
        public static string ExtruderDeleteCaption {
            get {
                return ResourceManager.GetString("ExtruderDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this extruder?.
        /// </summary>
        public static string ExtruderDeleteQuestion {
            get {
                return ResourceManager.GetString("ExtruderDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruder - .
        /// </summary>
        public static string ExtruderForConcat {
            get {
                return ResourceManager.GetString("ExtruderForConcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nozzle diameter (mm).
        /// </summary>
        public static string ExtruderNozzleDiameter {
            get {
                return ResourceManager.GetString("ExtruderNozzleDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extruder offset (mm).
        /// </summary>
        public static string ExtruderOffset {
            get {
                return ResourceManager.GetString("ExtruderOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut G-code.
        /// </summary>
        public static string ExtruderPFCutCode {
            get {
                return ResourceManager.GetString("ExtruderPFCutCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut distance (mm).
        /// </summary>
        public static string ExtruderPFCutDistance {
            get {
                return ResourceManager.GetString("ExtruderPFCutDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Cut pause (sec).
        /// </summary>
        public static string ExtruderPFCutPause {
            get {
                return ResourceManager.GetString("ExtruderPFCutPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Cut servo index.
        /// </summary>
        public static string ExtruderPFCutServeIndex {
            get {
                return ResourceManager.GetString("ExtruderPFCutServeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral angle (°).
        /// </summary>
        public static string ExtruderPFNeutralAngle {
            get {
                return ResourceManager.GetString("ExtruderPFNeutralAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber restart length (mm).
        /// </summary>
        public static string ExtruderPFRestartLength {
            get {
                return ResourceManager.GetString("ExtruderPFRestartLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo angle (°).
        /// </summary>
        public static string ExtruderPFServoAngle {
            get {
                return ResourceManager.GetString("ExtruderPFServoAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic extruders.
        /// </summary>
        public static string ExtrudersPlastic {
            get {
                return ResourceManager.GetString("ExtrudersPlastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling fan index.
        /// </summary>
        public static string FanIndex {
            get {
                return ResourceManager.GetString("FanIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer settings file (*.aup)|*.aup.
        /// </summary>
        public static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has cooling fan.
        /// </summary>
        public static string HasFan {
            get {
                return ResourceManager.GetString("HasFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has heated build plate.
        /// </summary>
        public static string HasHeatedTable {
            get {
                return ResourceManager.GetString("HasHeatedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerations.
        /// </summary>
        public static string HEADER_ACCELERATION {
            get {
                return ResourceManager.GetString("HEADER_ACCELERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build area.
        /// </summary>
        public static string HEADER_BUILD_AREA {
            get {
                return ResourceManager.GetString("HEADER_BUILD_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string HEADER_FEATURES {
            get {
                return ResourceManager.GetString("HEADER_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-code.
        /// </summary>
        public static string HEADER_G_CODE {
            get {
                return ResourceManager.GetString("HEADER_G_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string HEADER_OTHER {
            get {
                return ResourceManager.GetString("HEADER_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel speed.
        /// </summary>
        public static string HEADER_TRAVEL_SPEED {
            get {
                return ResourceManager.GetString("HEADER_TRAVEL_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (mm).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home position for X-axis (mm).
        /// </summary>
        public static string HomeXPosition {
            get {
                return ResourceManager.GetString("HomeXPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home position for Y-axis (mm).
        /// </summary>
        public static string HomeYPosition {
            get {
                return ResourceManager.GetString("HomeYPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home position for Z-axis (mm).
        /// </summary>
        public static string HomeZPosition {
            get {
                return ResourceManager.GetString("HomeZPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External shell acceleration (mm/sec²).
        /// </summary>
        public static string Inset0Acceleration {
            get {
                return ResourceManager.GetString("Inset0Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External shell jerk (mm/sec).
        /// </summary>
        public static string Inset0Jerk {
            get {
                return ResourceManager.GetString("Inset0Jerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth (mm).
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-lift on tool change (mm).
        /// </summary>
        public static string OnChangeExtruderUpMM {
            get {
                return ResourceManager.GetString("OnChangeExtruderUpMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular acceleartion (mm/sec²).
        /// </summary>
        public static string OtherAcceleration {
            get {
                return ResourceManager.GetString("OtherAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular jerk (mm/sec).
        /// </summary>
        public static string OthersJerk {
            get {
                return ResourceManager.GetString("OthersJerk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer can&apos;t be deleted.
        /// </summary>
        public static string PrinterInSessionCaption {
            get {
                return ResourceManager.GetString("PrinterInSessionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer is used by current session and can&apos;t be deleted.
        /// </summary>
        public static string PrinterInSessionText {
            get {
                return ResourceManager.GetString("PrinterInSessionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting printer....
        /// </summary>
        public static string RemoveCaption {
            get {
                return ResourceManager.GetString("RemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this printer?.
        /// </summary>
        public static string RemoveQuestion {
            get {
                return ResourceManager.GetString("RemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start G-code.
        /// </summary>
        public static string StartGCode {
            get {
                return ResourceManager.GetString("StartGCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new composite extruder.
        /// </summary>
        public static string TipAddNewCompositeExtruder {
            get {
                return ResourceManager.GetString("TipAddNewCompositeExtruder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new plastic extruder.
        /// </summary>
        public static string TipAddNewPlasticExtruder {
            get {
                return ResourceManager.GetString("TipAddNewPlasticExtruder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new printer.
        /// </summary>
        public static string TipAddNewPrinter {
            get {
                return ResourceManager.GetString("TipAddNewPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all printers.
        /// </summary>
        public static string TipExportPrinters {
            get {
                return ResourceManager.GetString("TipExportPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import printers.
        /// </summary>
        public static string TipImportPrinters {
            get {
                return ResourceManager.GetString("TipImportPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X/Y travel speed (mm/sec).
        /// </summary>
        public static string TravelSpeedXY {
            get {
                return ResourceManager.GetString("TravelSpeedXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z travel speed (mm/sec).
        /// </summary>
        public static string TravelSpeedZ {
            get {
                return ResourceManager.GetString("TravelSpeedZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable acceleration control.
        /// </summary>
        public static string UseAccelerations {
            get {
                return ResourceManager.GetString("UseAccelerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable jerk control.
        /// </summary>
        public static string UseJerks {
            get {
                return ResourceManager.GetString("UseJerks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (mm).
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X offset (mm).
        /// </summary>
        public static string XOffset {
            get {
                return ResourceManager.GetString("XOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y offset (mm).
        /// </summary>
        public static string YOffset {
            get {
                return ResourceManager.GetString("YOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z offset (mm).
        /// </summary>
        public static string ZOffset {
            get {
                return ResourceManager.GetString("ZOffset", resourceCulture);
            }
        }
    }
}
