//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura.Themes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support_en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support_en_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura.Themes.Localization.Support-en-EN", typeof(Support_en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom airgap thin layers count.
        /// </summary>
        public static string AirGapToBottom {
            get {
                return ResourceManager.GetString("AirGapToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top airgap thin layers count.
        /// </summary>
        public static string AirGapToUp {
            get {
                return ResourceManager.GetString("AirGapToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill pattern.
        /// </summary>
        public static string CellularType {
            get {
                return ResourceManager.GetString("CellularType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make airgaps.
        /// </summary>
        public static string DoAirGap {
            get {
                return ResourceManager.GetString("DoAirGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrusion width coefficient.
        /// </summary>
        public static string EWCoeffThin {
            get {
                return ResourceManager.GetString("EWCoeffThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate support.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate support in holes.
        /// </summary>
        public static string GenerateInternalSupport {
            get {
                return ResourceManager.GetString("GenerateInternalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate shell for support.
        /// </summary>
        public static string GeneratePerimeters {
            get {
                return ResourceManager.GetString("GeneratePerimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill density (%).
        /// </summary>
        public static string InfillPercent {
            get {
                return ResourceManager.GetString("InfillPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill angle (°).
        /// </summary>
        public static string InfillStartingAngle {
            get {
                return ResourceManager.GetString("InfillStartingAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick support layer height (mm).
        /// </summary>
        public static string RatioToMacroThick {
            get {
                return ResourceManager.GetString("RatioToMacroThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin support layer height (mm).
        /// </summary>
        public static string RatioToMacroThin {
            get {
                return ResourceManager.GetString("RatioToMacroThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max unsupported overhang angle (°).
        /// </summary>
        public static string SelfSupportAngle {
            get {
                return ResourceManager.GetString("SelfSupportAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick support printing speed (mm/sec).
        /// </summary>
        public static string SpeedThick {
            get {
                return ResourceManager.GetString("SpeedThick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin support printing speed (mm/sec).
        /// </summary>
        public static string SpeedThin {
            get {
                return ResourceManager.GetString("SpeedThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thick support.
        /// </summary>
        public static string THICK_HEADER {
            get {
                return ResourceManager.GetString("THICK_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thin support.
        /// </summary>
        public static string THIN_HEADER {
            get {
                return ResourceManager.GetString("THIN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal X/Y distance from model (mm).
        /// </summary>
        public static string XYDistanceFromObject {
            get {
                return ResourceManager.GetString("XYDistanceFromObject", resourceCulture);
            }
        }
    }
}
